const path = require('path');

module.exports={
    entry:'./src/app.js',
    mode:'development',
    output:{
        filename:'app.bundle.js',
        path:path.resolve(__dirname,'dist'),
    },
    module:{
        rules:[
            {
                test:/\.js$/,
                exclude:/(node_modules)/,
                use:{
                    loader:'babel-loader',
                    options:{
                        presets:['@babel/preset-env']
                    }
                }
            },
        ]
    },
    devServer:{
        open:true,
        static:{
            directory:path.join(__dirname,'dist'),
        },
        port:9000,
    }
};